/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package triggersmysql;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JoseDeskT
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
      setLocationRelativeTo(null);
      setResizable(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TXT_usuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTN_acceder = new javax.swing.JToggleButton();
        BTN_salir = new javax.swing.JToggleButton();
        lbl_logo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXT_contrasena = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(TXT_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 175, 117, -1));

        jLabel1.setText("USUARIO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 177, -1, -1));

        jLabel2.setText("CONTRASEÑA : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 202, -1, -1));

        BTN_acceder.setText("ACCEDER");
        BTN_acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_accederActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 231, -1, -1));

        BTN_salir.setText("SALIR");
        BTN_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_salirActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 231, 79, -1));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo.png"))); // NOI18N
        jPanel1.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 0, 312, -1));

        jLabel5.setText("V. 1.0");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));
        jPanel1.add(TXT_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 200, 117, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 162, 417, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_salirActionPerformed
        // TODO add your handling code here:

       
        System.exit(0);
        
    }//GEN-LAST:event_BTN_salirActionPerformed

    //metodo para validar inicio de sesion con la base de datos
    public void logeo(String user, String pass){
    String userName = "";
    String passWord = "";
    Conector baseDatos = new Conector().conectar();
    ResultSet resultado = baseDatos.consultar("SELECT * FROM login WHERE nombre ='"+TXT_usuario.getText()+"' && contrasena = '"+TXT_contrasena.getText()+"'");
        try {
            while(resultado.next()){
                userName = resultado.getString("nombre");
                passWord = resultado.getString("contrasena");
                
                
            } 
        if(userName.equals(user) && passWord.equals(pass) ){
        TriggerGenerator vt = new TriggerGenerator();
        vt.setVisible(true);
        this.dispose();
        }else{
        JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos!");
        } 
        
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }

    private void BTN_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_accederActionPerformed
        // TODO add your handling code here:
     if(TXT_usuario.getText().equals("") || TXT_contrasena.getText().equals("")){
     
         JOptionPane.showMessageDialog(null, "No deje los campos en blanco!");
         TXT_usuario.setText("");
         TXT_contrasena.setText("");
     }else{
     logeo(TXT_usuario.getText(),TXT_contrasena.getText());
     }
    }//GEN-LAST:event_BTN_accederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BTN_acceder;
    private javax.swing.JToggleButton BTN_salir;
    private javax.swing.JPasswordField TXT_contrasena;
    private javax.swing.JTextField TXT_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_logo;
    // End of variables declaration//GEN-END:variables
}
