/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package triggersmysql;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
/**
 *
 * @author JoseDeskT
 */
public class TriggerGenerator extends javax.swing.JFrame {

    DefaultTableModel tabla;
    /**
     * Creates new form TriggerGenerator
     */
    public TriggerGenerator() {
        initComponents();
        
        //Al momento de cargar la ventana se ejecuta el metodo y se vacia la lista que contiene 
        //los nombres de las conexiones en el combo
        setLocationRelativeTo(null);
        CMB_ListaConexiones.removeAllItems();
       CMB_ListaConexiones2.removeAllItems();
         ArrayList<String> lista = new ArrayList<String>();
        lista = llenar_combo_conexion();
        for(int i = 0; i<lista.size();i++){
        CMB_ListaConexiones.addItem(lista.get(i));
        CMB_ListaConexiones2.addItem(lista.get(i));
        
        
        }
   
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CMB_ListaConexiones = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        BTN_SeleccionarConexion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CMB_ListaTablasConexion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BTN_triggerInsertar = new javax.swing.JToggleButton();
        BTN_triggerUpdate = new javax.swing.JToggleButton();
        BTN_triggerDelete = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        CMB_ListaConexiones2 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        TXT_NombreConexion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXT_NombreTrigger = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TXT_FuncionTrigger = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TXT_TablaDelTrigger = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CMB_ListaTriggers = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador de Triggers para MySql Grupo 5");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Panel de generacion de Triggers"));

        jLabel1.setText("Lista de Conexiones.");

        BTN_SeleccionarConexion.setText("SELECCIONAR");
        BTN_SeleccionarConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SeleccionarConexionActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tablas "));

        jLabel2.setText("Tablas de la conexion seleccionada:");

        CMB_ListaTablasConexion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Esperanda Accion..." }));

        jLabel3.setText("Generar bitacora en tabla seleccionada");

        jButton1.setText("GENERAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Generar Trigger"));

        BTN_triggerInsertar.setText(" INSERT");
        BTN_triggerInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_triggerInsertarActionPerformed(evt);
            }
        });

        BTN_triggerUpdate.setText("UPDATE");

        BTN_triggerDelete.setText("DELETE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BTN_triggerUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_triggerInsertar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_triggerDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_triggerInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTN_triggerUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTN_triggerDelete)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CMB_ListaTablasConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addGap(6, 6, 6))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CMB_ListaTablasConexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CMB_ListaConexiones, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTN_SeleccionarConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CMB_ListaConexiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_SeleccionarConexion))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel de Control de Triggers"));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Conexiones"));

        jLabel6.setText("Nombre de la conexion:");

        jButton5.setText("SELECCIONAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addComponent(CMB_ListaConexiones2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CMB_ListaConexiones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Trigger"));

        TXT_NombreConexion.setEditable(false);

        jLabel7.setText("Conexion");

        TXT_NombreTrigger.setEditable(false);

        jLabel8.setText("Nombre del Trigger");

        jLabel9.setText("Se activa cuando:");

        TXT_FuncionTrigger.setEditable(false);

        jLabel10.setText("Tabla a la que pertenece");

        TXT_TablaDelTrigger.setEditable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(105, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TXT_TablaDelTrigger, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(TXT_FuncionTrigger, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_NombreTrigger, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_NombreConexion, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXT_NombreTrigger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addComponent(TXT_NombreConexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXT_TablaDelTrigger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXT_FuncionTrigger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Triggers de la Conexion"));

        jLabel4.setText("Nombre del trigger:");

        CMB_ListaTriggers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Esperando..." }));

        jButton2.setText("SELECCIONAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jLabel11.setText("ACCION DEL TRIGGER");

        jButton3.setText("ACTIVAR");

        jButton4.setText("DESACTIVAR");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CMB_ListaTriggers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CMB_ListaTriggers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Gestion de Triggers de MySql");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public ArrayList<String> llenar_combo_tablas(){
    String tipoConexion = String.valueOf(CMB_ListaConexiones.getSelectedItem());
        Conector baseDatos = new Conector().conectar();
    ArrayList<String> lista2 = new ArrayList<String>();
      ResultSet resultados = baseDatos.consultar("SHOW TABLES FROM "+tipoConexion+";"); 
       
        try{
           while(resultados.next()){
           lista2.add(resultados.getString("Tables_in_"+tipoConexion));
           }
            
        
        }catch(Exception e){
        e.printStackTrace();
        
        
        }
        
        return lista2;
        
    
    }
    
public ArrayList<String> llenar_combo_triggers(){
    String tipoConexion2 = String.valueOf(CMB_ListaConexiones2.getSelectedItem());
        Conector baseDatos = new Conector().conectar();
    ArrayList<String> lista3 = new ArrayList<String>();
      ResultSet resultados = baseDatos.consultar("SELECT TRIGGER_NAME FROM information_schema.`TRIGGERS` WHERE TRIGGER_SCHEMA LIKE '%"+tipoConexion2+"%'"); 
       
        try{
           while(resultados.next()){
           lista3.add(resultados.getString("TRIGGER_NAME"));
           }
            
        
        }catch(Exception e){
        e.printStackTrace();
        
        
        }
        
        return lista3;
        
    
    }
    private void BTN_SeleccionarConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SeleccionarConexionActionPerformed
        // TODO add your handling code here:
        //Obtiene el contenido del combo de las bases y a partir de crea una arrayList donde cargara las tablas
        //de la base a partir del metodo creado llamado llenar_combo_tablas();
        
        CMB_ListaTablasConexion.removeAllItems();
         ArrayList<String> lista2 = new ArrayList<String>();
        lista2 = llenar_combo_tablas();
        for(int i = 0; i<lista2.size();i++){
        CMB_ListaTablasConexion.addItem(lista2.get(i));
        
        
      
        }
    }//GEN-LAST:event_BTN_SeleccionarConexionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        CMB_ListaTablasConexion.removeAllItems();
         ArrayList<String> lista2 = new ArrayList<String>();
        lista2 = llenar_combo_tablas();
        for(int i = 0; i<lista2.size();i++){
        CMB_ListaTablasConexion.addItem(lista2.get(i));
        String nombreBase = String.valueOf(CMB_ListaConexiones.getSelectedItem());
        
        if(lista2.get(i).equals("auditoria")){
        JOptionPane.showMessageDialog(null, "No puede crear la tabla auditoria porque ya existe en la base seleccionada! ");
        break;
        }else{
        
        
        Conector baseDatos = new Conector().conectar();
        
        baseDatos.ejecutar("USE "+nombreBase+";");
        baseDatos.ejecutar("CREATE TABLE `auditoria`(\n" +
"	`id` INT(100) NOT NULL AUTO_INCREMENT,\n" +
"	`fecha` DATETIME NULL DEFAULT NULL,\n" +
"	`usuario` VARCHAR(50) NULL DEFAULT NULL,\n" +
"	`accion_realizada` VARCHAR(100) NULL DEFAULT NULL,\n" +
"	`ip_host` VARCHAR(15) NULL DEFAULT NULL,\n" +
"	`clave_primaria` VARCHAR(10) NULL DEFAULT NULL,\n" +
"        `nombre_tabla` VARCHAR(50) NULL DEFAULT NULL,\n" +
"	`valor_anterior` VARCHAR(50) NULL DEFAULT NULL,\n" +
"	`valor_nuevo` VARCHAR(50) NULL DEFAULT NULL,\n" +
"	PRIMARY KEY (`id`)\n" +
")\n" +
"COLLATE='latin1_swedish_ci'\n" +
"ENGINE=InnoDB\n" +
";");
        } }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BTN_triggerInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_triggerInsertarActionPerformed
        // TODO add your handling code here:
        String nombreBase = String.valueOf(CMB_ListaConexiones.getSelectedItem());
        String nombreTabla = String.valueOf(CMB_ListaTablasConexion.getSelectedItem());
        
        if(nombreBase.equals(null) || nombreTabla.equals(null)){
            JOptionPane.showMessageDialog(null, "Aun no hay una tabla seleccionada, por favor seleccione una tabla para la creacion del trigger!");
        }else{
        
        Conector baseDatos = new Conector().conectar();
        baseDatos.ejecutar("USE "+nombreBase+";");
        baseDatos.ejecutar("CREATE DEFINER=`root`@`localhost` TRIGGER `disparadorInsert_"+nombreTabla+"` AFTER INSERT ON `"+nombreTabla+"` FOR EACH ROW BEGIN\n" +
"INSERT into auditoria (fecha,usuario,accion_realizada,consulta_ejecutada,ip_host,clave_primaria,nombre_tabla,tipo_dato,\n" +
"valor_anterior,valor_nuevo)\n" +
"values (\n" +
"NOW(),\n" +
"CURRENT_USER(),\n" +
"'INSERT',\n" +
"'-----',\n" +
"(Select SUBSTRING_INDEX(host,':',1) as 'ip' \n" +
" From information_schema.processlist \n" +
" WHERE ID=connection_id()),\n" +
"(SELECT MAX(id) FROM "+nombreTabla+"),\n" +
"'"+nombreTabla+"',\n" +
"'-----',\n" +
"'-----',\n" +
"'-----'\n" +
");\n" +
"END");
        }
    }//GEN-LAST:event_BTN_triggerInsertarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //Obtiene el contenido del combo de las bases y a partir de crea una arrayList donde cargara las tablas
        //de la base a partir del metodo creado llamado llenar_combo_tablas();
        
        //Obtiene el contenido del combo de las bases y a partir de crea una arrayList donde cargara las tablas
        //de la base a partir del metodo creado llamado llenar_combo_tablas();
        
        CMB_ListaTriggers.removeAllItems();
         ArrayList<String> lista2 = new ArrayList<String>();
        lista2 = llenar_combo_triggers();
        for(int i = 0; i<lista2.size();i++){
        CMB_ListaTriggers.addItem(lista2.get(i));
        }
       
        //METODO PARA LLENAR LOS TXTS del TRIGGER
    }//GEN-LAST:event_jButton5ActionPerformed

    public  ArrayList<String> obtener_campos_triggers(){
        Conector baseDatos = new Conector().conectar();
    ArrayList<String> lista = new ArrayList<String>();
    String nombreTrigger = String.valueOf(CMB_ListaTriggers.getSelectedItem());
     ResultSet resultados = baseDatos.consultar("SELECT TRIGGER_NAME, TRIGGER_SCHEMA, EVENT_OBJECT_TABLE,EVENT_MANIPULATION \n" +
"FROM\n" +
"information_schema.`TRIGGERS` WHERE TRIGGER_NAME LIKE '"+nombreTrigger+"';"); 
       
        try{
           while(resultados.next()){
           lista.add(resultados.getString("TRIGGER_NAME"));
           lista.add(resultados.getString("TRIGGER_SCHEMA"));
           lista.add(resultados.getString("EVENT_OBJECT_TABLE"));
           lista.add(resultados.getString("EVENT_MANIPULATION"));
           }
            
        
        }catch(Exception e){
        e.printStackTrace();
        
        
        }
        
        return lista;
        
        
        
    
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Este boton se va encargar de llenar los datos del trigger para su revision
        //Seteamos los txt en blanco para que haya problemas de texto
        String funcion,nombreC,nombreT,tablaT;
        
        TXT_FuncionTrigger.setText("");
        TXT_NombreConexion.setText("");
        TXT_NombreTrigger.setText("");
        TXT_TablaDelTrigger.setText("");
        
        //Obtenemos cada uno de los campos y los almacenamos en varibales locales
      
        ArrayList<String> lista = obtener_campos_triggers();
       nombreT = lista.get(0);
       nombreC = lista.get(1);
       tablaT= lista.get(2);
       funcion = lista.get(3);
        
        //LLenamos los txt con los campos obtenidos anteriormente
        TXT_FuncionTrigger.setText(funcion);
        TXT_NombreConexion.setText(nombreC);
        TXT_NombreTrigger.setText(nombreT);
        TXT_TablaDelTrigger.setText(tablaT);
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TriggerGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TriggerGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TriggerGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TriggerGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TriggerGenerator().setVisible(true);
            }
        });
    }
    //metodo para obtener la lista de conexiones de la base de datos
    public static ArrayList<String> llenar_combo_conexion(){
        Conector baseDatos = new Conector().conectar();
    ArrayList<String> lista = new ArrayList<String>();
      ResultSet resultados = baseDatos.consultar("SELECT DISTINCT TABLE_SCHEMA  FROM information_schema.`TABLES`;"); 
       
        try{
           while(resultados.next()){
           lista.add(resultados.getString("TABLE_SCHEMA"));
           }
            
        
        }catch(Exception e){
        e.printStackTrace();
        
        
        }
        
        return lista;
        
        
        
    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_SeleccionarConexion;
    private javax.swing.JToggleButton BTN_triggerDelete;
    private javax.swing.JToggleButton BTN_triggerInsertar;
    private javax.swing.JToggleButton BTN_triggerUpdate;
    private javax.swing.JComboBox<String> CMB_ListaConexiones;
    private javax.swing.JComboBox<String> CMB_ListaConexiones2;
    private javax.swing.JComboBox<String> CMB_ListaTablasConexion;
    private javax.swing.JComboBox<String> CMB_ListaTriggers;
    private javax.swing.JTextField TXT_FuncionTrigger;
    private javax.swing.JTextField TXT_NombreConexion;
    private javax.swing.JTextField TXT_NombreTrigger;
    private javax.swing.JTextField TXT_TablaDelTrigger;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
